# This image build for cuda10.0 + cudnn7 + ros kinetic

FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

# Set default shell to bash
SHELL ["/bin/bash", "-c"]
ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive
ENV ROS_DISTRO kinetic
WORKDIR ${HOME}
RUN echo "Preparing system environment..."
RUN mv /root/.bashrc /root/bashrc.bak && \
    touch /root/.bashrc
RUN apt-get update -qq > /dev/null && apt-get install -y -qq sudo wget lsb-release iputils-ping > /dev/null && \
    apt-get install -y -qq build-essential libopencv-dev python-opencv libeigen3-dev vim htop sshfs nfs-common python-dev git python-pip python-all-dev libatlas-base-dev gfortran > /dev/null && \
    apt-get install -y -qq libopenblas-dev mpg123 > /dev/null && \
    rm -rf /var/lib/apt/lists/*
RUN wget -q https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    export PATH=/usr/local/bin:$PATH && \
    rm get-pip.py

RUN pip install --upgrade pip

# RUN git clone https://github.com/voutcn/g2o.git && cd g2o && sh init.sh

# ADD pip install pyopenssl before ROS install to fix build issue
RUN pip install -q -U bitarray pyzmq ujson requests gunicorn pymysql numpy pandas scipy scikit-learn gTTs awscli numba chardet pyopenssl > /dev/null
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 && \
    apt-get update -qq && \
    apt-get install -y -qq ros-kinetic-desktop-full && \
    rosdep init && \
    rosdep update && \
    echo "source /opt/ros/kinetic/setup.bash" >> /root/.bashrc && \
    source /root/.bashrc

RUN pip install torch torchvision

EXPOSE 22 80 8888
