# FROM nvidia/cudagl:10.0-devel-ubuntu16.04
FROM nvidia/cudagl:9.0-devel-ubuntu16.04
#FROM osrf/ros:kinetic-desktop-xenial

SHELL ["/bin/bash","-c"]

# Prerequisite linux tool for ROS 
RUN apt-get update -qq > /dev/null && apt-get install -y -qq sudo wget lsb-release iputils-ping > /dev/null && \
    apt-get install -y -qq build-essential vim htop sshfs nfs-common git net-tools && \
    rm -rf /var/lib/apt/lists/*


# CUDNN 7
ENV CUDNN_VERSION 7.4.1.5
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils \
            libcudnn7=$CUDNN_VERSION-1+cuda10.0


# ROS installation: kinetic
ENV ROS_DISTRO kinetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 && \
    apt-get update && apt-get install -y \
        apt-utils \
        ros-${ROS_DISTRO}-desktop-full \
        ros-${ROS_DISTRO}-serial \
        ros-${ROS_DISTRO}-teb-local-planner \
        ros-${ROS_DISTRO}-interactive-marker-proxy \
        ros-${ROS_DISTRO}-tf2-ros ros-${ROS_DISTRO}-rosbridge-server && \
    rosdep init && \
    rosdep update && \
    echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc && \
    source /root/.bashrc


# Jupyter installation
RUN apt-get update && apt-get install -y python-pip python3-pip
RUN pip install pip==19.3.1
RUN apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash
RUN apt-get -y install nodejs

RUN pip install jupyter ipywidgets jupyterlab bqplot pyyaml jupyros numpy==1.12.0 future==0.18.2
RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
RUN jupyter labextension install jupyter-ros
RUN jupyter nbextension enable --py --sys-prefix jupyros
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension


# Pytorch installation: cuda 9.0 + python 2.7 + pip
RUN pip install --no-cache-dir torch==1.0.1 -f https://download.pytorch.org/whl/cu90/stable torchvision typing
# Pytorch installation: cuda 10.0 + python 2.7 + pip
# RUN pip install --no-cache-dir torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/cu100/torch_stable.html


# packages to run examples
RUN pip install sidecar gdown h5py opencv-python
RUN pip install --upgrade cryptography matplotlib
RUN python -m easy_install --upgrade pyOpenSSL 
RUN jupyter labextension install @jupyter-widgets/jupyterlab-sidecar


# Bash completion
RUN rm /etc/apt/apt.conf.d/docker-clean && \
    apt-get install -y bash-completion

ENV QT_X11_NO_MITSHM=1


# Add a user with the same user_id as the user outside the container
# Requires a docker build argument `user_id`
ARG user_id=1000
ENV USERNAME developer
RUN useradd -U --uid ${user_id} -ms /bin/bash $USERNAME && \
    echo "$USERNAME:$USERNAME" | chpasswd && \
    adduser $USERNAME sudo && \
    chown -R $USERNAME /home/$USERNAME /root/ && \
    echo "$USERNAME ALL=NOPASSWD: ALL" >> /etc/sudoers.d/$USERNAME
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/$USERNAME/.bashrc


# Commands below run as the developer user
USER $USERNAME


CMD ["bash"]